site_name: Bukowski Database
site_url: https://bukowskiforum.com
theme:
  name: material
  custom_dir: overrides
  font:
    text: Crimson Pro
    code: Courier Prime
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: grey
      accent: deep orange
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: grey
      accent: deep orange
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: grey
      accent: deep orange
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress 
    - navigation.prune
    - navigation.path
    - content.tooltips
plugins:
  - search
  - privacy
  - macros

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      toc_depth : "1-1"

extra_javascript:
  - https://unpkg.com/tablesort@5.2.1/src/tablesort.js
  - https://unpkg.com/tablesort@5.2.1/src/sorts/tablesort.date.js
  - https://unpkg.com/tablesort@5.2.1/src/sorts/tablesort.number.js
  - javascripts/tablesort.js