name: Build Bukowski Database & Deploy via FTP
# this bad boy is too big to host on GitHub Pages, cloudflare, or any free service,so we're deploying to our own server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Prepare Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # 3) (optional) Cache pip packages to speed-up subsequent runs
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4) Install MkDocs & plugins
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5) Build the static site
      - name: Build bukowski database
        run: mkdocs build --clean        # output ends up in ./site

      # 6) Deploy the ./site folder via FTP
      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:      ${{ secrets.BUKOWSKIFORUM_HOST }}
          username:    ${{ secrets.BUKOWSKIFORUM_USER }}
          password:    ${{ secrets.BUKOWSKIFORUM_PASS }}
          protocol:    ftp               # (default) can be sftp if your host allows it
          port:        21                # change if your host uses a different port
          local-dir:   ./site            # what to upload
          server-dir:  /public/database/ # where to upload it
          # Set to true if you want to wipe remote dir before upload
          dangerous-clean-slate: false